### ISSUE TITLE
QR Code Scanner

### ISSUE THREAD

**Issue by RegiReis7** [rafaelwillen/union-services#11]
Add QR Code Scanner feature to get people's info through the code available on BI

- https://docs.expo.dev/versions/latest/sdk/bar-code-scanner/

YOUTUBE TUTORIAL

https://www.youtube.com/watch?v=LtbuOgoQJAg

**Comment by rafaelwillen** [comment]
O expo-barcode-scanner não consegue ler códigos QR do BI e nem sequer códigos mais simples como links do website, então essa feature ficará encerrada.
